HELIX_DBAPI = "pytds"  # Use the pure-Python driver on Cloud

[servers.SNDEMO]
host = "snpoc-synapse-ondemand.sql.azuresynapse.net"
database = "SNDEMO"
username = "SN_DEMO_USER_01"
password = "Ft2@qV5!mZ2K"

[servers.UGLAND]
host = "shipnetuglandanalytics-ondemand.sql.azuresynapse.net"
database = "UglandProdDB"
username = "SNUGLPRODUSER"
password = "sTutKrs66*"

[servers.LEMISSOLER]
host = "shipnetlemissoleranalytics-ondemand.sql.azuresynapse.net"
database = "LEMISSOLER"
username = "SN_LEM_USER_01"
password = "Ky6@qP4!zM7W"

[servers.NavShipping]
host = "shipnetnavshipanalytics-ondemand.sql.azuresynapse.net"
database = "NavShipping"
username = "SN_NAVSHIP_USER_01"
password = "K7!tSx#9Lr@2PfYq"

[servers.EPIC]
host = "shipnetepicanalytics-ondemand.sql.azuresynapse.net"
database = "EPIC"
username = "SN_EPIC_USER_01"
password = "V7g!rP9x#Q2b"

[servers.Emarat]
host = "shipnetemaratanalytics-ondemand.sql.azuresynapse.net"
database = "Emarat"
username = "SN_EMARAT_USER_01"
password = "K6#mN7*pL2@vZ5!nR2"

[servers.Unigas]
host = "shipnetunigasanalytics-ondemand.sql.azuresynapse.net"
database = "Unigas"
username = "SN_UNI_USER_01"
password = "Gx6#mQ$vN3"
